<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net472</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\ServiceControl.Transports\ServiceControl.Transports.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="NServiceBus" Version="7.4.4" />
        <PackageReference Include="App.Metrics.Reporting.Console" Version="4.*" />
    </ItemGroup>

    <ItemGroup>
      <None Update="original.txt">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>
    
</Project>
